export const GROCERY_LEXICON = [
  'abricots', 'ail', 'aires', 'ananas', 'artichauts', 'asperges', 'aubergines',
  'avocats', 'bacon', 'bananes', 'basilic', 'bœuf', 'betteraves', 'blettes',
  'bleu', 'brioche', 'brocoli', 'beurre', 'carottes', 'cannelle', 'câpres',
  'caramel', 'carcassis', 'cèpes', 'cerfeuil', 'cerises', 'champignons',
  'chocolat', 'chorizo', 'chou', 'chou-fleur', 'chou rouge', 'citrons',
  'citron vert', 'ciboulette', 'cumin', 'comté', 'concombres', 'coriandre',
  'courgettes', 'crème', 'crème fraîche', 'crevettes', 'croissants', 'curry',
  'dattes', 'emmental', 'échalotes', 'épinards', 'escargots', 'estragon',
  'farine', 'fenouil', 'figues', 'flan', 'fromage blanc', 'fromage râpé',
  'framboises', 'fraises', 'frites', 'fruits secs', 'gâteau', 'gingembre',
  'gnocchi', 'graines de sésame', 'gruyère', 'gruyère râpé', 'haricots verts',
  'herbes de Provence', 'huile', 'huile d’olive', 'jambon', 'jambon blanc',
  'jambon cru', 'jus d’orange', 'kiwis', 'lait', 'laitue', 'lardons',
  'lasagnes', 'lentilles', 'limonade', 'lisettes', 'macaroni', 'maïs',
  'mangue', 'margarine', 'mayonnaise', 'melon', 'menthe', 'miel', 'mozzarella',
  'moutarde', 'muscade', 'mûres', 'noix de muscade', 'oignons',
  'olives', 'oranges', 'origan', 'pain', 'pain de mie', 'pamplemousse',
  'paprika', 'pâtes', 'pates', 'pâtisson', 'poireaux', 'poires', 'poivre',
  'poivrons', 'pomme de terre', 'pommes', 'porc', 'pois chiches', 'poissons',
  'pollen', 'poulet', 'prunes', 'raisins', 'raspberries', 'ricotta',
  'riz', 'roquefort', 'romarin', 'safran', 'salade', 'saumon', 'sardines',
  'sauce tomate', 'saucisses', 'serpolet', 'sel', 'semoule', 'thé', 'thym',
  'tomates', 'tomates cerises', 'tortillas', 'tournedos', 'tuna', 'vanille',
  'veau', 'vinaigre', 'vinaigrette', 'yaourts'
]
